
theme: jekyll-theme-minimal
title: ChaosKitties Automation Testing
description: >- # The description
  Welcome to the Chaos Kitties Automation website! 
author: Curious Jen
avatar: "/assets/img/avatar-icon.png"
