###########################################################
### Welcome to ChaosKitties Automation Testing!
###########################################################
theme: jekyll-theme-minimal
############################
# --- details --- #
############################

# Name of website
title: ChaosKitties Automation Testing

# Your name to show in the footer
author: Curious Jen

###############################################
# --- List of links in the navigation bar --- #
###############################################
navbar-links:
  About: TBD
  Resources:
    - Something else

################
# --- Logo --- #
################
avatar: "/assets/img/avatar-icon.png"
