
theme: jekyll-theme-minimal
title: ChaosKitties Automation Testing
description: >- # The description
  Welcome to the Chaos Kitties Automation website!
baseurl: "" # Adjust if your site is in a subdirectory
author: Curious Jen
avatar: "/assets/img/avatar-icon.png"
